name: gif_search
description: Flutter application that seeks gifs

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.0.0+1
  cupertino_icons: ^0.1.2
  share: ^0.6.3+5
  transparent_image: ^1.0.0
  http: ^0.12.0+2
  flutter_statusbarcolor: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "icons/dollar.png"